source_list:
  - SB
  - OL
  - CP
  - ADDR

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id
    query : "(select * from testdb.TRANSACTIONSYNC where Internal_Member_Id = 'PC7135361') as t"

OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data
  filename: receipts_delta_GBR_14_10_2017.csv

CP:
  s3_conf:
    s3_bucket: mandeep-poc-bucket/emrcluster-dataframeexample-data/    
  filename: KC_Extract_1_20171009.csv

ADDR:
  mongodb_config:
    database: customer
    collection: address

target_list:
  # - REGIS_DIM
  # - CHILD_DIM
  - RTL_TXN_FCT

REGIS_DIM:
  tableName: REGIS_DIM
  sourceData:
    - CP
    - ADDR
  loadingQuery: >
    SELECT 
    FN_UUID() AS REGIS_KEY, REGIS_CNSM_ID as CNSM_ID, REGIS_CTY_CODE AS CTY_CODE,
    REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, INS_DT
    FROM 
    (SELECT 
    DISTINCT a.REGIS_CNSM_ID, CAST(a.REGIS_CTY_CODE AS SMALLINT), CAST(a.REGIS_ID as INTEGER), 
    a.REGIS_LTY_ID, a.REGIS_DATE, a.REGIS_CHANNEL, a.REGIS_GENDER, a.REGIS_CITY, 
    b.STATE, b.CITY, b.STREET, a.INS_DT
    FROM CP a join ADDR b
    on a.REGIS_CNSM_ID=b.consumer_id
    WHERE a.INS_DT = '2022-12-09'
    ) CP2
    
CHILD_DIM:
  tableName: CHILD_DIM
  sourceData:
    - CP
  loadingQuery: >
    SELECT FN_UUID() CHILD_KEY, REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, INS_DT
    FROM (SELECT DISTINCT REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, INS_DT
    FROM CP
    WHERE INS_DT = '2022-12-09'
    AND CHILD_ID IS NOT NULL
    ) CP
    
RTL_TXN_FCT:
  tableName: RTL_TXN_FCT
  sourceTable:
    - REGIS_DIM
    - CHILD_DIM
  sourceData:
    - SB
    - OL
  loadingQuery: >
    SELECT FN_UUID() as RTL_TXN_KEY,
    app_transaction_id, internal_member_id, location_external_reference, transaction_type_id, transaction_timestamp, activity_timestamp, activity_app_date, transaction_retail_value, transaction_profit_value, transaction_base_point_value, transaction_point_value, transaction_won_value, event_name, issue_audit_user, transaction_external_reference, cancel_timestamp, cancel_audit, Cancel_Audit_User, REG.ins_dt, loyalty_id, process_id, mobile_uid, mobile_os, receipt_status, receipt_total, receipt_date, points_earned, products, store, process_flag, locale, msg_code, program_id, country_code, r_cre_time, doublesided_flag, base_point_value, sblp_transaction_id, receipt_type, r_last_modified_time, acp_id, ereceipt_file_type, regis_key, cnsm_id, cty_code, regis_id, regis_date, lty_id, regis_channel, regis_gender, regis_city
    FROM SB TXN 
    LEFT OUTER JOIN OL REC
    ON TXN.APP_TRANSACTION_ID=REC.SBLP_TRANSACTION_ID
    LEFT OUTER JOIN REGIS_DIM REG
    ON REC.LOYALTY_ID = REG.CNSM_ID
    WHERE TXN.INS_DT = '2022-12-09'
    AND (REC.INS_DT = '2022-12-09' OR REC.INS_DT is NULL)

s3_conf:
  s3_bucket: mandeep-poc-bucket/emrcluster-dataframeexample-data/
  staging_dir: pg_staging

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: DATAMART.REGIS_DIM
  #query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT
