source_list:
  - SB
  - OL
  - CP
  - ADDR

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id
    query : "(select * from testdb.TRANSACTIONSYNC where Internal_Member_Id = 'PC7135361') as t"

OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data
  filename: receipts_delta_GBR_14_10_2017.csv

CP:
  s3_conf:
    s3_bucket: mandeep-poc-bucket/emrcluster-dataframeexample-data/    
  filename: KC_Extract_1_20171009.csv

ADDR:
  mongodb_config:
    database: customer
    collection: address

target_list:
  # - REGIS_DIM
  # - CHILD_DIM
  - RTL_TXN_FCT

REGIS_DIM:
  tableName: REGIS_DIM
  sourceData:
    - CP
    - ADDR
  loadingQuery: >
    SELECT 
    FN_UUID() AS REGIS_KEY, REGIS_CNSM_ID as CNSM_ID, REGIS_CTY_CODE AS CTY_CODE,
    REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, INS_DT
    FROM 
    (SELECT 
    DISTINCT a.REGIS_CNSM_ID, CAST(a.REGIS_CTY_CODE AS SMALLINT), CAST(a.REGIS_ID as INTEGER), 
    a.REGIS_LTY_ID, a.REGIS_DATE, a.REGIS_CHANNEL, a.REGIS_GENDER, a.REGIS_CITY, 
    b.STATE, b.CITY, b.STREET, a.INS_DT
    FROM CP a join ADDR b
    on a.REGIS_CNSM_ID=b.consumer_id
    WHERE a.INS_DT = '2022-12-09'
    ) CP2
    
CHILD_DIM:
  tableName: CHILD_DIM
  sourceData:
    - CP
  loadingQuery: >
    SELECT FN_UUID() CHILD_KEY, REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, INS_DT
    FROM (SELECT DISTINCT REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, INS_DT
    FROM CP
    WHERE INS_DT = '2022-12-09'
    AND CHILD_ID IS NOT NULL
    ) CP
    
RTL_TXN_FCT:
  tableName: RTL_TXN_FCT
  sourceTable:
    - REGIS_DIM
    - CHILD_DIM
  sourceData:
    - SB
    - OL
  loadingQuery: >
    SELECT 
    FN_UUID() as RTL_TXN_KEY, CAST(TXN.APP_TRANSACTION_ID AS STRING) AS TXN_ID, SIZE(split(REC.PRODUCTS,',')) as TXN_ITEM_QTY,
    TRANSACTION_POINT_VALUE AS TXN_LOY_VAL_STD_CCY, 0 as TXN_GROSS_MNY_STD_CCY, TRANSACTION_RETAIL_VALUE AS TXN_GROSS_MNY_LCL_CCY,
    -1 AS MNY_LCL_CCY_TYPE_KEY, TRANSACTION_EXTERNAL_REFERENCE AS RTL_TXN_TYPE_KEY, ACTIVITY_TIMESTAMP AS TXN_TS,
    CAST(ACTIVITY_TIMESTAMP) AS TXN_DT_KEY, HOUR(ACTIVITY_TIMESTAMP) AS TXN_TM_HOUR, MINUTE(ACTIVITY_TIMESTAMP) AS TXN_TM_MINUTE,
    SECOND(ACTIVITY_TIMESTAMP) AS TXN_TM_SECOND, '-1' AS CHNL_KEY, REG.CNSM_ID AS CNSM_ID, 
    "@NULL@" AS RTL_TXN_EXT_DEC_1, "@NULL@" AS RTL_TXN_EXT_DEC_12, REC.BASE_POINT_VALUE AS RTL_TXN_EXT_DEC_3,
    MOBILE_UID AS RTL_TXN_EXT_CHAR_1, MOBILE_OS AS RTL_TXN_EXT_CHAR_2, PRODUCTS AS RTL_TXN_EXT_CHAR_3,
    RECEIPT_STATUS AS RTL_TXN_EXT_CHAR_4, CAST(MSG_CODE AS BIGINT) AS RTL_TXN_EXT_CHAR_5, TXN.INS_DT AS INS_DT
    FROM SB TXN 
    LEFT OUTER JOIN OL REC
    ON TXN.APP_TRANSACTION_ID=REC.SBLP_TRANSACTION_ID
    LEFT OUTER JOIN REGIS_DIM
    ON REC.LOYALTY_ID = REG.CNSM_ID
    WHERE TXN.INS_DT = '2022-12-09'
    AND (REC.INS_DT = '2022-12-09' OR REC.INS_DT is NULL)

s3_conf:
  s3_bucket: mandeep-poc-bucket/emrcluster-dataframeexample-data/
  staging_dir: pg_staging

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: DATAMART.REGIS_DIM
  #query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT
