source_list:
  - SB
  - OL
  - CP
  - ADDR

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id
    query : "(select * from testdb.TRANSACTIONSYNC where Internal_Member_Id = 'PC7135361') as t"

OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data
  filename: receipts_delta_GBR_14_10_2017.csv

CP:
  s3_conf:
    s3_bucket: mandeep-poc-bucket/emrcluster-dataframeexample-data/    
  filename: KC_Extract_1_20171009.csv

ADDR:
  mongodb_config:
    database: customer
    collection: address

target_list:
  - REGIS_DIM
  - CHILD_DIM

REGIS_DIM:
  tableName: REGIS_DIM
  sourceData:
    - CP
    - ADDR
  loadingQuery: >
    SELECT 
    FN_UUID() AS REGIS_KEY, REGIS_CNSM_ID as CNSM_ID, REGIS_CTY_CODE AS CTY_CODE,
    REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, INS_DT
    FROM 
    (SELECT 
    DISTINCT a.REGIS_CNSM_ID, CAST(a.REGIS_CTY_CODE AS SMALLINT), CAST(a.REGIS_ID as INTEGER), 
    a.REGIS_LTY_ID, a.REGIS_DATE, a.REGIS_CHANNEL, a.REGIS_GENDER, a.REGIS_CITY, 
    b.STATE, b.CITY, b.STREET, a.INS_DT
    FROM CP a join ADDR b
    on a.REGIS_CNSM_ID=b.consumer_id
    WHERE a.INS_DT = CURRENT_DATE and b.INS_DT = CURRENT_DATE
    ) CP2
    
CHILD_DIM:
  tableName: DATAMART.CHILD_DIM
  sourceData:
    - CP
  loadingQuery: >
    SELECT FN_UUID() CHILD_KEY, REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, current_Timestamp
    FROM (SELECT DISTINCT REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, current_Timestamp
    FROM CP
    WHERE CAST(INS_TS AS DATE) = CURRENT_DATE
    AND CHILD_ID IS NOT NULL
    ) CP
    


s3_conf:
  s3_bucket: mandeep-poc-bucket/emrcluster-dataframeexample-data/
  staging_dir: pg_staging

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: DATAMART.REGIS_DIM
  #query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT
